# Configuración del servidor
server.address=0.0.0.0
server.port=8080

# Configuración de la base de datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-solitary-unit-ahtc33qu-pooler.c-3.us-east-1.aws.neon.tech/neondb

spring.datasource.username=neondb_owner
spring.datasource.password=npg_P4YaINXQuDh6
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SSL es obligatorio en Render
spring.datasource.hikari.data-source-properties.sslmode=require


# Configuración de Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html


# Configuración de Jackson
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false